### ISSUE TITLE
GSS ---> ValueError: the input array must be have a shape == (.., ..,[ ..,] 3)), got (1136617, 3)

### ISSUE THREAD

**Issue by yongtaowang327** [facebookresearch/WyPR#5]
Hello there!

When I ran `python selective_search_3d_run.py --split trainval --dataset s3dis --data_path ../wypr/dataset/s3dis/ --cgal_path ../wypr/dataset/s3dis/s3dis_all_points`, there was a ValueError:

Area_1/conferenceRoom_1
Traceback (most recent call last):
  File "selective_search_3d_run.py", line 135, in \<module>
    run_s3dis(names, masks)
  File "selective_search_3d_run.py", line 120, in run_s3dis
    _run_gss(args, scene_id)
  File "selective_search_3d_run.py", line 68, in _run_gss
    proposals = _selective_search_one(pcd, scene_id, mask, FLAGS)
  File "/content/WyPR/gss/utils.py", line 108, in _selective_search_one
    pcd_color_converted = color_space_3d.convert_color(pcd_color, color_formate)
  File "/content/WyPR/gss/color_space_3d.py", line 19, in convert_color
    return converters\[name](pcd_color)
  File "/content/WyPR/gss/color_space_3d.py", line 38, in to_HSV
    return (255 * skimage.color.rgb2hsv(pcd_color)).astype(numpy.uint8)
  File "/usr/local/lib/python3.7/dist-packages/skimage/color/colorconv.py", line 248, in rgb2hsv
    arr = _prepare_colorarray(rgb)
  File "/usr/local/lib/python3.7/dist-packages/skimage/color/colorconv.py", line 145, in _prepare_colorarray
    raise ValueError(msg)
ValueError: the input array must be have a shape == (.., ..,[ ..,] 3)), got (1136617, 3)

And i wonder if i wrote the correct '--cgal_path'.

Any help woud be greatly appreciated. Thanks!

**Comment by bishoyroufael** [comment]
I am facing the same issue. I think the `cgal_path` is related to the outcome from `preprocess_for_gss.py` but that script as well didn't work for me.

**Comment by yongtaowang327** [comment]
Thanks for your reply! I think u are right.

As for the `preprocess_for_gss.py`, i modified the code by changing L56 to `points = np.load(os.path.join(data_path, scene_id+'_annot.npy'))`, and it seems to work.https://github.com/facebookresearch/WyPR/blob/1b4c9af4e5d97440f684565ff3bfc994ebf4d65a/wypr/dataset/s3dis/preprocess_for_gss.py#L56

**Comment by yongtaowang327** [comment]
Thanks for your reply! I think u are right.

As for the `preprocess_for_gss.py`, i modified the code by changing L56 to `points = np.load(os.path.join(data_path, scene_id+'_annot.npy'))`, and it seems to work.
https://github.com/facebookresearch/WyPR/blob/1b4c9af4e5d97440f684565ff3bfc994ebf4d65a/wypr/dataset/s3dis/preprocess_for_gss.py#L56

**Comment by bishoyroufael** [comment]
I have changed lines 55 and 56 to 
```
F0 = np.load(os.path.join(data_path, scene_id , 'shape.npy'))   # Edited
points = np.load(os.path.join(data_path, scene_id, 'vert.npy')) # Edited
```

I have seen that in the script `shape_det/preprocess.py` this line `parser = argparse.ArgumentParser('prepare the s3dis dataset')
` which seemed confusing because for `s3dis` the `docs/RUNNING.md` says check the `wypr/dataset/s3dis/README.md` . in the script `shape_det/preprocess.py` it has:
```
F0 = np.load(os.path.join(data_path, 'cgal_output', scene_id+'_shape.npy'))
points = np.load(os.path.join('../wypr/dataset/scannet/scannet_all_points', scene_id+'_vert.npy'))
```
So I expected points to be the `vert.npy` array generated by `wypr/dataset/s3dis/prepare_all_points.py` and not the `_annot.npy` . Correct me if I am wrong.
Also I changed `data_path ='s3dis_processed'` to `data_path = 's3dis_all_points'`

**Comment by yongtaowang327** [comment]
In the `wypr/dataset/s3dis/prepare_all_points.py`, it seems that `vert.npy` and `_annot.npy` have the same part of the data that store the xyzrgb of the points. 
https://github.com/facebookresearch/WyPR/blob/1b4c9af4e5d97440f684565ff3bfc994ebf4d65a/wypr/dataset/s3dis/prepare_all_points.py#L90
In the `preprocess_for_gss.py`, it only need the xyz of the points from the `points`, so i think these two files have the same effect. And the `_shape.npy` and the `shape.npy` are same too. I can't remember exactly. Correct me if I am wrong.

**Comment by bishoyroufael** [comment]
You are correct yup. Did you manage to generate the gss proposals using `selective_search_3d_run.py` ?. For me it's running but taking too long and is aboarting at the end due to memory issues. I am running this on a machine with the following specs:
```
Processor: 2 x Intel Xeon Gold 6134 CPU
Ram: 128GB
GPU: RTX 2080TI + 1080TI
```

**Comment by yongtaowang327** [comment]
I'm faced the same problem when i generate the gss proposals of s3dis. And i got a much worse result compared to the paper after i deleted the scans which caused the memory issue. I have no idea why it happened yet :(

**Comment by jason718** [comment]
hey guys, sorry for the late reply. Can you share the error message of the memory issue?

**Comment by jason718** [comment]
> You are correct yup. Did you manage to generate the gss proposals using `selective_search_3d_run.py` ?. For me it's running but taking too long and is aboarting at the end due to memory issues. I am running this on a machine with the following specs:
> 
> ```
> Processor: 2 x Intel Xeon Gold 6134 CPU
> Ram: 128GB
> GPU: RTX 2080TI + 1080TI
> ```

thanks for the feedback. How slow is it on your side?

**Comment by bishoyroufael** [comment]
I have rerun the script using a single process `--n_proc=1`  to limit the memory usage being utilized by more than a process. This is still running since yesterday night. I would estimate this to end take 12 hours to end. Using multiprocessing would help reducing that to nearly half of the time. I have unfortunately cleared the terminal memory issue but it was something regarding multiprocessing used. Also at some stages a warning is raised `RuntimeWarning: invalid value encountered in true_divide` . I don't know if that's fine to ignore or something is not correct.

**Comment by jason718** [comment]
> I have rerun the script using a single process `--n_proc=1` to limit the memory usage being utilized by more than a process. This is still running since yesterday night. I would estimate this to end take 12 hours to end. Using multiprocessing would help reducing that to nearly half of the time. I have unfortunately cleared the terminal memory issue but it was something regarding multiprocessing used. Also at some stages a warning is raised `RuntimeWarning: invalid value encountered in true_divide` . I don't know if that's fine to ignore or something is not correct.

1. the mem issue seems strange. I was using the multi-processing fine on my machine, and i often set --n_proc to a very high value (e.g., 32). 
2. The `RuntimeWarning` suggests that it is dividing something by 0, which is usually not safe to ignore. If this happens again, can you point to me the exact line of code and the scene name? 
3. Can you share the command you are running?

**Comment by bishoyroufael** [comment]
Using a single process is still going fine until now without any warning. it's running through the files one by one and is at Area 4 currently. I would provide an update if that finished successfully. Also it's worth mentioning that `if __name__ == "__main__":` should be added before any function that is using multiprocessing. That's because on windows all the multiprocessing must be guarded. on linux that shouldn't be a problem. For example in `wypr/dataset/s3dis/process.py` : 

https://github.com/facebookresearch/WyPR/blob/1b4c9af4e5d97440f684565ff3bfc994ebf4d65a/wypr/dataset/s3dis/process.py#L70

https://github.com/facebookresearch/WyPR/blob/1b4c9af4e5d97440f684565ff3bfc994ebf4d65a/wypr/dataset/s3dis/process.py#L99

https://github.com/facebookresearch/WyPR/blob/1b4c9af4e5d97440f684565ff3bfc994ebf4d65a/wypr/dataset/s3dis/process.py#L125

https://github.com/facebookresearch/WyPR/blob/1b4c9af4e5d97440f684565ff3bfc994ebf4d65a/wypr/dataset/s3dis/process.py#L171

All these methods should be guarded.

**Comment by jason718** [comment]
thanks for the suggestion. I wasn't familiar with windows stuff, I'll add it.

**Comment by bishoyroufael** [comment]
As far as I remember the warning was generated here: 
https://github.com/facebookresearch/WyPR/blob/1b4c9af4e5d97440f684565ff3bfc994ebf4d65a/gss/utils.py#L146
Command I am running `python selective_search_3d_run.py --dataset s3dis --split trainval --data_path ..\\wypr\\dataset\\s3dis\\ --cgal_path ..\\wypr\\dataset\\s3dis\\s3dis_processed\\ --n_proc 1`

**Comment by bishoyroufael** [comment]
I would also appreciate it if you can upload the pretrained weights because the links in the docs are broken

**Comment by jason718** [comment]
> As far as I remember the warning was generated here:
> https://github.com/facebookresearch/WyPR/blob/1b4c9af4e5d97440f684565ff3bfc994ebf4d65a/gss/utils.py#L146
> 
> 
> Command I am running `python selective_search_3d_run.py --dataset s3dis --split trainval --data_path ..\\wypr\\dataset\\s3dis\\ --cgal_path ..\\wypr\\dataset\\s3dis\\s3dis_processed\\ --n_proc 1`

if the divisor gets 0 in this line, it only means both areas are 0. That says, invalid 3D bounding boxes are generated. Does this warning occur often? Or is it only occasionally occurring for certain scene?

**Comment by bishoyroufael** [comment]
It occurred occasionally in some scenes. I have a feeling that this might be an issue because of `s3dis/preprocess_for_gss.py`. Since this script didn't work out of the box, are the suggested edits by me or @yongtaowang327 correct?

Also what exactly is the script `shape_det/preprocess.py` doing? It has this line `parser = argparse.ArgumentParser('prepare the s3dis dataset')` which is misleading because it's not mentioned in the docs of `s3dis` and it seems to do something similar to `s3dis/preprocess_for_gss.py`

**Comment by yongtaowang327** [comment]
https://github.com/facebookresearch/WyPR/blob/1b4c9af4e5d97440f684565ff3bfc994ebf4d65a/gss/utils.py#L118-L120
I think x2y2z2 should be the max value of xyz of the box. So i changed L118-L120 in `utils.py` to
```
x2 = boxes[:,0] + boxes[:,3] / 2
y2 = boxes[:,1] + boxes[:,4] / 2
z2 = boxes[:,2] + boxes[:,5] / 2
```
Is it correct? And is it helpful for this problem?

**Comment by bishoyroufael** [comment]
I hit the first warning a while ago:
```
Area_4/lobby_1
d:\wypr\gss\utils.py:146: RuntimeWarning: invalid value encountered in true_divide
  o = inter / (area[i] + area[I[:last-1]] - inter)
```

**Comment by bishoyroufael** [comment]
> https://github.com/facebookresearch/WyPR/blob/1b4c9af4e5d97440f684565ff3bfc994ebf4d65a/gss/utils.py#L118-L120
> 
> 
> I think x2y2z2 should be the max value of xyz of the box. So i changed L118-L120 in `utils.py` to
> ```
> x2 = boxes[:,0] + boxes[:,3] / 2
> y2 = boxes[:,1] + boxes[:,4] / 2
> z2 = boxes[:,2] + boxes[:,5] / 2
> ```
> 
> Is it correct? And is it helpful for this problem?

Did that improve the results?

**Comment by yongtaowang327** [comment]
> > https://github.com/facebookresearch/WyPR/blob/1b4c9af4e5d97440f684565ff3bfc994ebf4d65a/gss/utils.py#L118-L120
> > 
> > I think x2y2z2 should be the max value of xyz of the box. So i changed L118-L120 in `utils.py` to
> > ```
> > x2 = boxes[:,0] + boxes[:,3] / 2
> > y2 = boxes[:,1] + boxes[:,4] / 2
> > z2 = boxes[:,2] + boxes[:,5] / 2
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Is it correct? And is it helpful for this problem?
> 
> Did that improve the results?

I just modified the code before i ran the whole process. I'm not sure whether it could improve the results.
