### ISSUE TITLE
ModuleNotFoundError: No module named 'wypr.modeling.models.seg_det_net'

### ISSUE THREAD

**Issue by yongtaowang327** [facebookresearch/WyPR#7]
When I ran `python tools/train.py`, there was a ModuleNotFoundError:
```
python tools/train.py model=seg_det_net_ts \
    distrib_backend=ddp backbone=pointnet2 num_point=40000 \
    batch_size=32 learning_rate=0.003 seg_pseudo_label_th=0.9 \
    hydra.run.dir=/path/to/outputs/

Traceback (most recent call last):
  File "tools/train.py", line 29, in my_app
    model = get_model(cfg)
  File "/content/WyPR/wypr/modeling/models/__init__.py", line 9, in get_model
    from wypr.modeling.models.seg_det_net import WyPR_SegDetTSNet as model
ModuleNotFoundError: No module named 'wypr.modeling.models.seg_det_net'
```
I wonder if there should be a `wypr/modeling/models/seg_det_net.py`. And i can't find the script.

**Comment by jason718** [comment]
thanks for pointing out. I'll upload the missing file soon. Sorry for the inconvenience.

**Comment by NCTU-VRDL** [comment]
Hi @jason718,

Is the file updated? Thanks.
